// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeHiringProj.Models;

namespace PrimeHiringProj.Migrations
{
    [DbContext(typeof(PrimeHiringDBContext))]
    [Migration("20211117221507_DevTeamsRelation")]
    partial class DevTeamsRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrimeHiringProj.Models.Candidate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("linkedIn")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nativeLanguage")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pricePerHour")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("profilePicture")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("technology")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("yearsOfExperience")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("PrimeHiringProj.Models.DevTeam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeamMembersHireDates")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TeamMembersLeaveDates")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TeamMembersNames")
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("id");

                    b.ToTable("DevTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
